import { AREAS } from './catalogue.js';
import type { Expect, Fixture, Scenario, Step } from './types.js';

/**
 * Renders the catalogue as the human checklist.
 *
 * The document is generated rather than written because a checklist maintained beside the
 * suite becomes fiction within two phases: the same failure mode `schemas:check` exists to
 * prevent. What a reader sees here is what the runner executes, or, for the manual area,
 * exactly what nobody executed.
 */
export function renderCatalogue(): string {
  const lines: string[] = [];
  const automated = AREAS.flatMap((area) => area.scenarios).filter((s) => s.mode === 'auto').length;
  const manual = AREAS.flatMap((area) => area.scenarios).filter((s) => s.mode === 'manual').length;

  lines.push('# Acceptance scenarios');
  lines.push('');
  lines.push(
    '<!-- Generated by `pnpm acceptance:docs` from tools/acceptance/src/scenarios. Do not edit. -->',
  );
  lines.push('');
  lines.push(
    'Every scenario is one thing a person does with the `lore` binary. The automated ones are',
  );
  lines.push(
    'executed by `pnpm acceptance` on macOS, Windows and Linux; the manual ones are a checklist,',
  );
  lines.push('because a terminal, a person or a clean machine cannot be simulated honestly.');
  lines.push('');
  lines.push(`${automated} automated, ${manual} checked by hand.`);
  lines.push('');
  lines.push('```bash');
  lines.push('pnpm build && pnpm acceptance         # the whole suite');
  lines.push('pnpm acceptance -t lifecycle          # one area');
  lines.push('```');
  lines.push('');
  lines.push(
    'Adding a scenario means adding a row to `tools/acceptance/src/scenarios/`, then running',
  );
  lines.push('`pnpm acceptance:docs`. This file is checked in CI and fails when it is stale.');
  lines.push('');

  for (const area of AREAS) {
    lines.push(`## ${area.title}`);
    lines.push('');
    lines.push(area.summary);
    lines.push('');
    for (const scenario of area.scenarios) {
      lines.push(...renderScenario(scenario));
    }
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function renderScenario(scenario: Scenario): string[] {
  const lines: string[] = [];
  const marker = scenario.mode === 'manual' ? ' (by hand)' : '';
  lines.push(`### \`${scenario.id}\`${marker}`);
  lines.push('');
  lines.push(`**${scenario.title}**`);
  lines.push('');
  lines.push(`Proves: ${scenario.proves}`);
  if (scenario.regression !== undefined) {
    lines.push('');
    lines.push(`Locks down the defect in #${scenario.regression}.`);
  }
  if (scenario.skip !== undefined) {
    lines.push('');
    lines.push(`Not run on ${scenario.skip.platforms.join(', ')}: ${scenario.skip.reason}`);
  }
  lines.push('');
  lines.push(`Starting point: ${describeFixture(scenario.fixture)}`);
  lines.push('');

  for (const [index, step] of scenario.steps.entries()) {
    const body = describeStep(step);
    lines.push(scenario.mode === 'manual' ? `- [ ] ${body}` : `${index + 1}. ${body}`);
    const expectation = step.action === 'note' ? step.expect : describeExpect(stepExpect(step));
    if (expectation !== null && expectation !== undefined && expectation !== '') {
      lines.push(
        scenario.mode === 'manual' ? `      Expect: ${expectation}` : `   Expect: ${expectation}`,
      );
    }
  }
  lines.push('');
  return lines;
}

function describeFixture(fixture: Fixture): string {
  const parts: string[] = [];
  const files = Object.keys(fixture.files ?? {}).length;
  if (fixture.generated !== undefined) {
    parts.push(
      `a generated corpus of ${fixture.generated.documents} documents with ${fixture.generated.sectionsPerDocument} sections each`,
    );
  } else if (files > 0) {
    parts.push(`${files} source file${files === 1 ? '' : 's'}`);
  } else {
    parts.push('an empty directory');
  }
  const setup = fixture.setup ?? [];
  if (setup.length > 0) {
    parts.push(
      `already set up with ${setup
        .map((step) =>
          step === 'build-large' ? '`lore build --allow-large-project`' : `\`lore ${step}\``,
        )
        .join(' and ')}`,
    );
  }
  return `${parts.join(', ')}.`;
}

function stepExpect(step: Step): Expect | undefined {
  return 'expect' in step && typeof step.expect === 'object' ? step.expect : undefined;
}

export function describeStep(step: Step): string {
  if (step.describe !== undefined && step.action !== 'note') return step.describe;

  switch (step.action) {
    case 'run':
      return `Run \`lore ${step.args.join(' ')}\`${step.json === true ? ' with `--json`' : ''}.`;
    case 'run-in':
      return `Run \`lore ${step.args.join(' ')}\`${step.json === true ? ' with `--json`' : ''} in \`${step.project}\`.`;
    case 'write':
      return step.atomic === true
        ? `Save \`${step.path}\` the way an editor does, by writing a sibling file and renaming over it.`
        : `Write \`${step.path}\`.`;
    case 'empty-sources':
      return 'Empty every source file, leaving the paths in place.';
    case 'symlink':
      return `Create \`${step.path}\` as a symbolic link to a directory outside the project.`;
    case 'clone':
      return `Copy the sources and configuration to a second absolute path (\`${step.as}\`).`;
    case 'corrupt':
      return `Flip every bit of the byte at offset ${step.offset} in \`${step.path}\`.`;
    case 'external':
      return `Run \`${step.command} ${step.args.join(' ')}\`${step.whenMissing === 'skip' ? ', where that tool exists' : ''}.`;
    case 'interrupt':
      return step.afterOutput === undefined
        ? `Start \`lore ${step.args.join(' ')}\` and send ${step.signal} after ${step.afterMs} ms${(step.repeat ?? 1) > 1 ? `, ${step.repeat} times` : ''}.`
        : `Start \`lore ${step.args.join(' ')}\`, wait for \`/${step.afterOutput}/\` in its output, then send ${step.signal} ${step.afterMs} ms later${(step.repeat ?? 1) > 1 ? `, ${step.repeat} times` : ''}.`;
    case 'concurrent':
      return `Start \`lore ${step.background.join(' ')}\`, then run \`lore ${step.foreground.join(' ')}\` ${step.afterMs} ms later.`;
    case 'identical':
      return step.as === 'bytes'
        ? `Compare \`${step.left.path}\` in both projects byte for byte.`
        : `Compare \`${step.left.path}\` in both projects as JSON.`;
    case 'record':
      return 'Note which builds exist and which one is active.';
    case 'unchanged':
      return 'Confirm `builds/` and the active pointer are exactly as they were.';
    case 'note':
      return step.text;
  }
}

export function describeExpect(expect: Expect | undefined): string {
  if (expect === undefined) return '';
  const parts: string[] = [];

  if (expect.exitCode !== undefined) {
    parts.push(expect.exitCode === 0 ? 'it succeeds' : `it exits ${expect.exitCode}`);
  }
  if (expect.errorCode !== undefined) parts.push(`the error is \`${expect.errorCode}\``);
  if (expect.stdoutIsJson === true) parts.push('stdout parses as JSON on its own');

  for (const [stream, text] of [
    ['stdout', expect.stdout],
    ['stderr', expect.stderr],
  ] as const) {
    if (text === undefined) continue;
    if (text.empty === true) parts.push(`${stream} is empty`);
    if (text.contains !== undefined && text.contains.length > 0) {
      parts.push(`${stream} mentions ${text.contains.map(quote).join(', ')}`);
    }
    if (text.excludes !== undefined && text.excludes.length > 0) {
      parts.push(`${stream} never mentions ${text.excludes.map(quote).join(', ')}`);
    }
    if (text.matches !== undefined && text.matches.length > 0) {
      parts.push(`${stream} matches ${text.matches.map((p) => `\`/${p}/\``).join(', ')}`);
    }
    for (const occurrence of text.occurrences ?? []) {
      parts.push(
        `${stream} shows \`/${occurrence.pattern}/\` at least ${occurrence.atLeast} times`,
      );
    }
  }

  for (const assertion of expect.json ?? []) {
    const path = `\`${assertion.path}\``;
    if (assertion.equals !== undefined)
      parts.push(`${path} is ${JSON.stringify(assertion.equals)}`);
    if (assertion.matches !== undefined) parts.push(`${path} matches \`/${assertion.matches}/\``);
    if (assertion.exists === true) parts.push(`${path} is present`);
    if (assertion.exists === false) parts.push(`${path} is absent`);
    if (assertion.atLeast !== undefined) parts.push(`${path} is at least ${assertion.atLeast}`);
    if (assertion.equalsCapture !== undefined) {
      parts.push(`${path} is the ${assertion.equalsCapture} build`);
    }
    if (assertion.differsFromCapture !== undefined) {
      parts.push(`${path} differs from the ${assertion.differsFromCapture} build`);
    }
  }

  if (parts.length === 0) return '';
  return `${parts.join(', ')}.`;
}

function quote(value: string): string {
  return `"${value}"`;
}
